/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ScoreUpdateParams {
    /** The new integer score to assign. */
    intScore?: number;
    /** The new boolean score to assign. */
    binaryScore?: boolean;
    /** The reasoning for the score update. */
    reasoning?: string;
}
