/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scorecard from "../../../../../api/index";
import * as core from "../../../../../core";

export const PromptUpdateParams: core.serialization.Schema<
    serializers.PromptUpdateParams.Raw,
    Scorecard.PromptUpdateParams
> = core.serialization.object({
    isArchived: core.serialization.property("is_archived", core.serialization.boolean().optional()),
    isProd: core.serialization.property("is_prod", core.serialization.boolean().optional()),
});

export declare namespace PromptUpdateParams {
    interface Raw {
        is_archived?: boolean | null;
        is_prod?: boolean | null;
    }
}
