/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scorecard from "../../../../../api/index";
import * as core from "../../../../../core";
import { PromptCreateParamsModelParamsValue } from "../../types/PromptCreateParamsModelParamsValue";

export const PromptCreateParams: core.serialization.Schema<
    serializers.PromptCreateParams.Raw,
    Scorecard.PromptCreateParams
> = core.serialization.object({
    promptTemplate: core.serialization.property("prompt_template", core.serialization.string()),
    name: core.serialization.string().optional(),
    parentId: core.serialization.property("parent_id", core.serialization.string().optional()),
    description: core.serialization.string().optional(),
    modelParams: core.serialization.property(
        "model_params",
        core.serialization.record(core.serialization.string(), PromptCreateParamsModelParamsValue.optional()).optional()
    ),
    tag: core.serialization.string().optional(),
    isProd: core.serialization.property("is_prod", core.serialization.boolean().optional()),
    projectId: core.serialization.property("project_id", core.serialization.number().optional()),
});

export declare namespace PromptCreateParams {
    interface Raw {
        prompt_template: string;
        name?: string | null;
        parent_id?: string | null;
        description?: string | null;
        model_params?: Record<string, PromptCreateParamsModelParamsValue.Raw | null | undefined> | null;
        tag?: string | null;
        is_prod?: boolean | null;
        project_id?: number | null;
    }
}
