/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Scorecard from "../../../../../api";
import * as core from "../../../../../core";

export const ScoreUpdateParams: core.serialization.Schema<
    serializers.ScoreUpdateParams.Raw,
    Scorecard.ScoreUpdateParams
> = core.serialization.object({
    intScore: core.serialization.property("int_score", core.serialization.number().optional()),
    binaryScore: core.serialization.property("binary_score", core.serialization.boolean().optional()),
    reasoning: core.serialization.string().optional(),
});

export declare namespace ScoreUpdateParams {
    interface Raw {
        int_score?: number | null;
        binary_score?: boolean | null;
        reasoning?: string | null;
    }
}
