/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Scorecard from "../../../../api";
import * as core from "../../../../core";

export const TestrecordCreateParamsModelDebugInfoValue: core.serialization.Schema<
    serializers.TestrecordCreateParamsModelDebugInfoValue.Raw,
    Scorecard.TestrecordCreateParamsModelDebugInfoValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.number(),
    core.serialization.number(),
    core.serialization.string(),
]);

export declare namespace TestrecordCreateParamsModelDebugInfoValue {
    type Raw = number | number | string;
}
