/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Scorecard from "../../../../api";
import * as core from "../../../../core";

export const TestrecordCreateParamsCustomInputsValue: core.serialization.Schema<
    serializers.TestrecordCreateParamsCustomInputsValue.Raw,
    Scorecard.TestrecordCreateParamsCustomInputsValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("../../..")).FileUrl),
    core.serialization.string(),
]);

export declare namespace TestrecordCreateParamsCustomInputsValue {
    type Raw = serializers.FileUrl.Raw | string;
}
