/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scorecard from "../../../../api/index";
import * as core from "../../../../core";
import { FileUrl } from "../../../types/FileUrl";

export const TestcaseUpdateParamsCustomInputsValue: core.serialization.Schema<
    serializers.TestcaseUpdateParamsCustomInputsValue.Raw,
    Scorecard.TestcaseUpdateParamsCustomInputsValue
> = core.serialization.undiscriminatedUnion([
    FileUrl,
    core.serialization.lazyObject(() => serializers.JsonObject),
    core.serialization.string(),
    core.serialization.number(),
    core.serialization.number(),
    core.serialization.boolean(),
]);

export declare namespace TestcaseUpdateParamsCustomInputsValue {
    type Raw = FileUrl.Raw | serializers.JsonObject.Raw | string | number | number | boolean;
}
