/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scorecard from "../../../../api/index";
import * as core from "../../../../core";
import { FileUrl } from "../../../types/FileUrl";

export const TestcaseCreateParamsCustomInputsValue: core.serialization.Schema<
    serializers.TestcaseCreateParamsCustomInputsValue.Raw,
    Scorecard.TestcaseCreateParamsCustomInputsValue
> = core.serialization.undiscriminatedUnion([
    FileUrl,
    core.serialization.lazyObject(async () => (await import("../../..")).JsonObject),
    core.serialization.string(),
    core.serialization.number(),
    core.serialization.number(),
    core.serialization.boolean(),
]);

export declare namespace TestcaseCreateParamsCustomInputsValue {
    type Raw = FileUrl.Raw | serializers.JsonObject.Raw | string | number | number | boolean;
}
