/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface RunCreateParams {
    testsetId?: number;
    scoringConfigId?: number;
    status?: string;
    /** Optional. The model parameters to use for this run. */
    modelParams?: Record<string, unknown>;
    source?: string;
    notes?: string;
    promptTemplate?: string;
    metrics?: number[];
}
