/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         testsetId: 1,
 *         scoringConfigId: 2,
 *         status: "RUNNING_EXECUTION",
 *         modelParams: {
 *             "param1": "value1",
 *             "param2": "value2"
 *         }
 *     }
 */
export interface RunCreateParams {
    testsetId?: number;
    scoringConfigId?: number;
    status?: string;
    modelParams?: Record<string, unknown>;
    source?: string;
    notes?: string;
    promptTemplate?: string;
}
