/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "../../../../index";

/**
 * @example
 *     {
 *         status: Scorecard.RunStatus.Pending
 *     }
 */
export interface UpdateStatusParams {
    status: Scorecard.RunStatus;
}
