/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "../../../../index";

/**
 * @example
 *     {}
 */
export interface TestrecordCreateParams {
    testsetId?: number;
    testcaseId?: number;
    /** The user query that was executed for the testrecord. */
    userQuery?: string;
    /** The context that was used while generating the testrecord. */
    context?: string;
    /** The response generated by the model. */
    response?: string;
    /** The ideal response. */
    ideal?: string;
    customInputs?: Record<string, Scorecard.TestrecordCreateParamsCustomInputsValue | undefined>;
    customOutputs?: Record<string, Scorecard.TestrecordCreateParamsCustomOutputsValue | undefined>;
    customLabels?: Record<string, Scorecard.TestrecordCreateParamsCustomLabelsValue | undefined>;
    /** The prompt used to generate the response. */
    prompt?: string;
    /** The model parameters used to generate the response. */
    modelParams?: Record<string, Scorecard.TestrecordCreateParamsModelParamsValue | undefined>;
    /** Debug information generated by Scorecard during the execution of the testrecord. */
    modelDebugInfo?: Record<string, Scorecard.TestrecordCreateParamsModelDebugInfoValue | undefined>;
}
