/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "Scoring Config Name",
 *         description: "Description of the scoring config",
 *         metrics: [1, 2, 3]
 *     }
 */
export interface ScoringConfigCreateParams {
    name?: string;
    description?: string;
    metrics?: number[];
}
