/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import * as Scorecard from "../../../api";
import * as core from "../../../core";

export const ScoreExecutionParams: core.serialization.Schema<
    serializers.ScoreExecutionParams.Raw,
    Scorecard.ScoreExecutionParams
> = core.serialization.object({
    scoringModelName: core.serialization.property("scoring_model_name", core.serialization.string()),
    runId: core.serialization.property("run_id", core.serialization.number()),
    testsetId: core.serialization.property("testset_id", core.serialization.number()),
    token: core.serialization.string(),
    useGlobalScoringConfig: core.serialization.property(
        "use_global_scoring_config",
        core.serialization.boolean().optional()
    ),
});

export declare namespace ScoreExecutionParams {
    interface Raw {
        scoring_model_name: string;
        run_id: number;
        testset_id: number;
        token: string;
        use_global_scoring_config?: boolean | null;
    }
}
