/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scorecard from "../../../../api/index";
import * as core from "../../../../core";

export const PromptCreateParamsModelParamsValue: core.serialization.Schema<
    serializers.PromptCreateParamsModelParamsValue.Raw,
    Scorecard.PromptCreateParamsModelParamsValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.number(),
    core.serialization.number(),
    core.serialization.string(),
    core.serialization.boolean(),
]);

export declare namespace PromptCreateParamsModelParamsValue {
    type Raw = number | number | string | boolean;
}
