/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Scorecard from "../../../../../api";
import * as core from "../../../../../core";

export const RunCreateParams: core.serialization.Schema<serializers.RunCreateParams.Raw, Scorecard.RunCreateParams> =
    core.serialization.object({
        testsetId: core.serialization.property("testset_id", core.serialization.number().optional()),
        scoringConfigId: core.serialization.property("scoring_config_id", core.serialization.number().optional()),
        status: core.serialization.string().optional(),
        modelParams: core.serialization.property(
            "model_params",
            core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
        ),
        source: core.serialization.string().optional(),
        notes: core.serialization.string().optional(),
        promptTemplate: core.serialization.property("prompt_template", core.serialization.string().optional()),
    });

export declare namespace RunCreateParams {
    interface Raw {
        testset_id?: number | null;
        scoring_config_id?: number | null;
        status?: string | null;
        model_params?: Record<string, unknown> | null;
        source?: string | null;
        notes?: string | null;
        prompt_template?: string | null;
    }
}
