/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scorecard from "../../../../../api/index";
import * as core from "../../../../../core";
import { RunStatus } from "../../../../types/RunStatus";

export const UpdateStatusParams: core.serialization.Schema<
    serializers.UpdateStatusParams.Raw,
    Scorecard.UpdateStatusParams
> = core.serialization.object({
    status: RunStatus,
});

export declare namespace UpdateStatusParams {
    interface Raw {
        status: RunStatus.Raw;
    }
}
