/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Scorecard from "../../../../../api";
import * as core from "../../../../../core";

export const UpdateStatusParams: core.serialization.Schema<
    serializers.UpdateStatusParams.Raw,
    Scorecard.UpdateStatusParams
> = core.serialization.object({
    status: core.serialization.lazy(async () => (await import("../../../..")).RunStatus),
});

export declare namespace UpdateStatusParams {
    interface Raw {
        status: serializers.RunStatus.Raw;
    }
}
