/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AppCreateRunParams {
    testsetId: number;
    scoringConfigId: number;
    status?: string;
    modelParams?: Record<string, unknown>;
}
