/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "../index";

/**
 * Custom variable model with name, description, role and data type.
 */
export interface CustomVariable {
    name: string;
    description?: string;
    role: Scorecard.RoleEnum;
    dataType: Scorecard.DataTypeEnum;
}
