/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "..";

/**
 * Custom schema model with an ordered list of custom variables.
 */
export interface CustomSchemaOutput {
    /** Ordered list of custom variables */
    variables?: Scorecard.CustomVariable[];
}
