/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "..";

export interface ExecutionParams {
    scoringModelName: string;
    runId: number;
    testsetId: number;
    apiToken: string;
    modelUnderTest: Scorecard.ModelParams;
    promptTemplate: string;
    instantScoring?: boolean;
}
