/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "../index";

export interface Grade {
    userId?: string;
    /** The ID of the grade. */
    id?: number;
    /** The ID of the run that created the grade. */
    runId?: number;
    /** The ID of the testcase associated with the grade. */
    testcaseId?: number;
    /** The ID of the testrecord for which the grade was created. */
    testrecordId?: number;
    /** The ID of the metric used to compute the grade. */
    metricId?: number;
    /** The binary score assigned to the grade. */
    binaryScore?: boolean;
    /** The integer score assigned to the grade. */
    intScore?: number;
    /** The reasoning for the assigned score. */
    reasoning?: string;
    /** Indicates if a human should assign a grade. */
    humanEval?: boolean;
    /** The status of the grade. */
    status?: Scorecard.ScoreStatus;
    /** The error message if the grade was not created successfully. */
    errorMessage?: string;
    /** when the grade was created. */
    createdAt?: Date;
    /** when the grade was last updated. */
    updatedAt?: Date;
}
