/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "..";

export interface Grade {
    id?: number;
    runId?: number;
    testcaseId?: number;
    testrecordId?: number;
    metricId?: number;
    userId?: string;
    binaryScore?: boolean;
    intScore?: number;
    reasoning?: string;
    humanEval?: boolean;
    status?: Scorecard.ScoreStatus;
    errorMessage?: string;
}
