/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Grade {
    id?: number;
    runId?: number;
    testcaseId?: number;
    testrecordId?: number;
    metricId?: number;
    binaryScore?: boolean;
    intScore?: number;
    reasoning?: string;
    humanEval?: boolean;
}
