/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type IngestionMethod = "csv" | "logging";

export const IngestionMethod = {
    Csv: "csv",
    Logging: "logging",
} as const;
