/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "..";

/**
 * The value of the JSON object, which can be a dictionary, list, string, integer, float, boolean, or None.
 */
export type JsonObjectOutputValue =
    | Record<string, Scorecard.JsonObject>
    | Scorecard.JsonObject[]
    | string
    | number
    | number
    | boolean;
