/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "..";

export interface JsonObject {
    /** The value of the JSON object, which can be a dictionary, list, string, integer, float, boolean, or None. */
    value?: Scorecard.JsonObjectOutputValue;
}
