/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "../index";

export interface PaginatedTestcaseResponse {
    count: number;
    next?: string;
    previous?: string;
    /** The list of Testcases retrieved in this page. */
    results: Scorecard.TestCase[];
}
