/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Enum for role types.
 */
export type RoleEnum = "input" | "output" | "label" | "metadata";

export const RoleEnum = {
    Input: "input",
    Output: "output",
    Label: "label",
    Metadata: "metadata",
} as const;
