/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Run {
    id?: number;
    /** The creation date and time of the run. */
    createdAt?: Date;
    /** The last time the run was updated. */
    updatedAt?: Date;
    /** The start time of the run. */
    executionStartTime?: Date;
    /** The end time of the run. */
    executionEndTime?: Date;
    /** The testset that was executed in this run. */
    testsetId?: number;
    /** The current status of the run. */
    status?: string;
    /** The maximum number of testcases to run. */
    limitTestcases?: number;
    /** How the run was created. */
    source?: string;
    /** The model parameters used when generating the run. */
    modelParams?: Record<string, unknown>;
    /** Notes about the run. */
    notes?: string;
    /** The ID of the scoring configuration the run uses. */
    scoringConfigId?: number;
    /** The prompt template to be used while executing the run. */
    promptTemplate?: string;
    /** The start time of scoring the run's results. */
    scoringStartTime?: Date;
    /** The end time of scoring the run's results. */
    scoringEndTime?: Date;
}
