/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RunStatus =
    | "pending"
    | "awaiting_execution"
    | "running_execution"
    | "awaiting_scoring"
    | "running_scoring"
    | "awaiting_human_scoring"
    | "completed";

export const RunStatus = {
    Pending: "pending",
    AwaitingExecution: "awaiting_execution",
    RunningExecution: "running_execution",
    AwaitingScoring: "awaiting_scoring",
    RunningScoring: "running_scoring",
    AwaitingHumanScoring: "awaiting_human_scoring",
    Completed: "completed",
} as const;
