/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ScoringConfig {
    /** The organization this resource belongs to. */
    orgId?: string;
    /** The user this record belongs to. */
    userId?: string;
    id?: number;
    name?: string;
    description?: string;
    config?: Record<string, unknown>;
    isArchived?: boolean;
    metrics?: number[];
    createdAt?: Date;
    /** The ID of the project the scoring config belongs to. */
    projectId?: number;
}
