/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ScoreStatus = "pending" | "error" | "completed";

export const ScoreStatus = {
    Pending: "pending",
    Error: "error",
    Completed: "completed",
} as const;
