/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ScoreExecutionParams {
    scoringModelName: string;
    runId: number;
    testsetId: number;
    token: string;
    useGlobalScoringConfig?: boolean;
}
