/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ScoringParams {
    modelVersion: string;
    runId: number;
    testsetId: number;
    token: string;
    limitTestcases?: number;
}
