/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "../index";

export interface Span {
    children: Scorecard.Span[];
    timestamp: Date;
    traceId: string;
    spanId: string;
    parentSpanId: string;
    traceState: string;
    spanName: string;
    spanKind: string;
    serviceName: string;
    resourceAttributes: Record<string, string>;
    scopeName: string;
    scopeVersion: string;
    spanAttributes: Record<string, string>;
    duration: number;
    statusCode: string;
    statusMessage: string;
    eventsTimestamp: Date[];
    eventsName: string[];
    eventsAttributes: Record<string, string>[];
    linksTraceId: string[];
    linksSpanId: string[];
    linksTraceState: string[];
    linksAttributes: Record<string, string>[];
}
