/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "..";

export interface TestCase {
    id?: number;
    createdAt?: Date;
    testsetId: number;
    userQuery: string;
    context?: string;
    response?: string;
    ideal?: string;
    fullPrompt?: string;
    customInputs?: Scorecard.TestCaseCustomInputs;
    customLabels?: Scorecard.TestCaseCustomLabels;
}
