/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TestSetExternal {
    id?: number;
    createdAt?: Date;
    name?: string;
    description?: string;
    usingRetrieval?: boolean;
    ingestionMethod?: string;
    numTestcases?: number;
    published?: boolean;
    updatedAt?: Date;
    isArchived?: boolean;
    projectId?: number;
    customInputsSchema?: Record<string, unknown>;
    customLabelsSchema?: Record<string, unknown>;
    customOutputsSchema?: Record<string, unknown>;
}
