/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TestCaseCreate {
    testsetId: number;
    userQuery: string;
    context?: string;
    response?: string;
    ideal?: string;
}
