/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TestcaseBatchDeletionResponse {
    /** The IDs of the testcases that were deleted. */
    ids: number[];
    /** The message indicating the testcases were deleted. */
    detail: string;
}
