/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "../index";

export type TestCaseCustomLabelsValue = string | Scorecard.FileUrl | Scorecard.JsonObject;
