/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "../index";

export type TestCaseCustomInputsValue = Scorecard.FileUrl | Scorecard.JsonObject | string | number | number | boolean;
