/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "../../..";

export type TestcaseCreateParamsCustomLabelsValue = string | Scorecard.FileUrl | Scorecard.JsonObject;
