/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scorecard from "../../../../../api/index";
import * as core from "../../../../../core";
import { CustomSchema } from "../../../../types/CustomSchema";

export const TestsetCreateParams: core.serialization.Schema<
    serializers.TestsetCreateParams.Raw,
    Scorecard.TestsetCreateParams
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    usingRetrieval: core.serialization.property("using_retrieval", core.serialization.boolean().optional()),
    customSchema: core.serialization.property("custom_schema", CustomSchema.optional()),
});

export declare namespace TestsetCreateParams {
    interface Raw {
        name: string;
        description?: string | null;
        using_retrieval?: boolean | null;
        custom_schema?: CustomSchema.Raw | null;
    }
}
