/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scorecard from "../../../../api/index";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.traces.get.Response.Raw, Scorecard.Span[]> =
    core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Span));

export declare namespace Response {
    type Raw = serializers.Span.Raw[];
}
