/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scorecard from "../../../../api/index";
import * as core from "../../../../core";
import { TestCase } from "../../../types/TestCase";

export const Response: core.serialization.Schema<serializers.testcase.batchCopy.Response.Raw, Scorecard.TestCase[]> =
    core.serialization.list(TestCase);

export declare namespace Response {
    type Raw = TestCase.Raw[];
}
