/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const AppCreateRunParams: core.serialization.Schema<
    serializers.AppCreateRunParams.Raw,
    Scorecard.AppCreateRunParams
> = core.serialization.unknown();

export declare namespace AppCreateRunParams {
    type Raw = unknown;
}
