/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const AppTestRecordCreate: core.serialization.Schema<
    serializers.AppTestRecordCreate.Raw,
    Scorecard.AppTestRecordCreate
> = core.serialization.unknown();

export declare namespace AppTestRecordCreate {
    type Raw = unknown;
}
