/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const AppTestSetCreate: core.serialization.Schema<serializers.AppTestSetCreate.Raw, Scorecard.AppTestSetCreate> =
    core.serialization.unknown();

export declare namespace AppTestSetCreate {
    type Raw = unknown;
}
