/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const BodyTextExtractTextExtractPost: core.serialization.ObjectSchema<
    serializers.BodyTextExtractTextExtractPost.Raw,
    Scorecard.BodyTextExtractTextExtractPost
> = core.serialization.object({
    file: core.serialization.string(),
});

export declare namespace BodyTextExtractTextExtractPost {
    interface Raw {
        file: string;
    }
}
