/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const BodyStartGithubWorkflowStartGithubWorkflowPost: core.serialization.Schema<
    serializers.BodyStartGithubWorkflowStartGithubWorkflowPost.Raw,
    Scorecard.BodyStartGithubWorkflowStartGithubWorkflowPost
> = core.serialization.unknown();

export declare namespace BodyStartGithubWorkflowStartGithubWorkflowPost {
    type Raw = unknown;
}
