/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scorecard from "../../api/index";
import * as core from "../../core";

export const CreateGithubWorkflowParams: core.serialization.Schema<
    serializers.CreateGithubWorkflowParams.Raw,
    Scorecard.CreateGithubWorkflowParams
> = core.serialization.unknown();

export declare namespace CreateGithubWorkflowParams {
    type Raw = unknown;
}
