/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const CreateGithubWorkflowParams: core.serialization.ObjectSchema<
    serializers.CreateGithubWorkflowParams.Raw,
    Scorecard.CreateGithubWorkflowParams
> = core.serialization.object({
    repoFullName: core.serialization.property("repo_full_name", core.serialization.string()),
    testsetId: core.serialization.property("testset_id", core.serialization.string()),
    scoringConfigId: core.serialization.property("scoring_config_id", core.serialization.string()),
});

export declare namespace CreateGithubWorkflowParams {
    interface Raw {
        repo_full_name: string;
        testset_id: string;
        scoring_config_id: string;
    }
}
