/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const CreateRunParams: core.serialization.Schema<serializers.CreateRunParams.Raw, Scorecard.CreateRunParams> =
    core.serialization.unknown();

export declare namespace CreateRunParams {
    type Raw = unknown;
}
