/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const CustomSchemaInput: core.serialization.ObjectSchema<
    serializers.CustomSchemaInput.Raw,
    Scorecard.CustomSchemaInput
> = core.serialization.object({
    variables: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).CustomVariable))
        .optional(),
});

export declare namespace CustomSchemaInput {
    interface Raw {
        variables?: serializers.CustomVariable.Raw[] | null;
    }
}
