/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scorecard from "../../api/index";
import * as core from "../../core";
import { RoleEnum } from "./RoleEnum";
import { DataTypeEnum } from "./DataTypeEnum";

export const CustomVariable: core.serialization.ObjectSchema<serializers.CustomVariable.Raw, Scorecard.CustomVariable> =
    core.serialization.object({
        name: core.serialization.string(),
        description: core.serialization.string().optional(),
        role: RoleEnum,
        dataType: core.serialization.property("data_type", DataTypeEnum),
    });

export declare namespace CustomVariable {
    interface Raw {
        name: string;
        description?: string | null;
        role: RoleEnum.Raw;
        data_type: DataTypeEnum.Raw;
    }
}
