/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const CustomVariable: core.serialization.ObjectSchema<serializers.CustomVariable.Raw, Scorecard.CustomVariable> =
    core.serialization.object({
        name: core.serialization.string(),
        description: core.serialization.string().optional(),
        role: core.serialization.lazy(async () => (await import("..")).RoleEnum),
        dataType: core.serialization.property(
            "data_type",
            core.serialization.lazy(async () => (await import("..")).DataTypeEnum)
        ),
    });

export declare namespace CustomVariable {
    interface Raw {
        name: string;
        description?: string | null;
        role: serializers.RoleEnum.Raw;
        data_type: serializers.DataTypeEnum.Raw;
    }
}
