/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scorecard from "../../api/index";
import * as core from "../../core";
import { CustomVariable } from "./CustomVariable";

export const CustomSchema: core.serialization.ObjectSchema<serializers.CustomSchema.Raw, Scorecard.CustomSchema> =
    core.serialization.object({
        variables: core.serialization.list(CustomVariable).optional(),
    });

export declare namespace CustomSchema {
    interface Raw {
        variables?: CustomVariable.Raw[] | null;
    }
}
