/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const CustomSchema: core.serialization.ObjectSchema<serializers.CustomSchema.Raw, Scorecard.CustomSchema> =
    core.serialization.object({
        variables: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).CustomVariable))
            .optional(),
    });

export declare namespace CustomSchema {
    interface Raw {
        variables?: serializers.CustomVariable.Raw[] | null;
    }
}
