/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const ExecutionParams: core.serialization.Schema<serializers.ExecutionParams.Raw, Scorecard.ExecutionParams> =
    core.serialization.unknown();

export declare namespace ExecutionParams {
    type Raw = unknown;
}
