/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scorecard from "../../api/index";
import * as core from "../../core";

export const FileUrl: core.serialization.ObjectSchema<serializers.FileUrl.Raw, Scorecard.FileUrl> =
    core.serialization.object({
        url: core.serialization.string(),
        name: core.serialization.string().optional(),
    });

export declare namespace FileUrl {
    interface Raw {
        url: string;
        name?: string | null;
    }
}
