/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const Grade: core.serialization.ObjectSchema<serializers.Grade.Raw, Scorecard.Grade> = core.serialization.object(
    {
        id: core.serialization.number().optional(),
        runId: core.serialization.property("run_id", core.serialization.number().optional()),
        testcaseId: core.serialization.property("testcase_id", core.serialization.number().optional()),
        testrecordId: core.serialization.property("testrecord_id", core.serialization.number().optional()),
        metricId: core.serialization.property("metric_id", core.serialization.number().optional()),
        binaryScore: core.serialization.property("binary_score", core.serialization.boolean().optional()),
        intScore: core.serialization.property("int_score", core.serialization.number().optional()),
        reasoning: core.serialization.string().optional(),
        humanEval: core.serialization.property("human_eval", core.serialization.boolean().optional()),
    }
);

export declare namespace Grade {
    interface Raw {
        id?: number | null;
        run_id?: number | null;
        testcase_id?: number | null;
        testrecord_id?: number | null;
        metric_id?: number | null;
        binary_score?: boolean | null;
        int_score?: number | null;
        reasoning?: string | null;
        human_eval?: boolean | null;
    }
}
