/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const JsonObject: core.serialization.ObjectSchema<serializers.JsonObject.Raw, Scorecard.JsonObject> =
    core.serialization.object({
        value: core.serialization.lazy(async () => (await import("..")).JsonObjectOutputValue).optional(),
    });

export declare namespace JsonObject {
    interface Raw {
        value?: serializers.JsonObjectOutputValue.Raw | null;
    }
}
