/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scorecard from "../../api/index";
import * as core from "../../core";

export const JsonObjectOutputValue: core.serialization.Schema<
    serializers.JsonObjectOutputValue.Raw,
    Scorecard.JsonObjectOutputValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.record(
        core.serialization.string(),
        core.serialization.lazyObject(async () => (await import("..")).JsonObject)
    ),
    core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).JsonObject)),
    core.serialization.string(),
    core.serialization.number(),
    core.serialization.number(),
    core.serialization.boolean(),
]);

export declare namespace JsonObjectOutputValue {
    type Raw =
        | Record<string, serializers.JsonObject.Raw>
        | serializers.JsonObject.Raw[]
        | string
        | number
        | number
        | boolean;
}
