/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const LibDtoTypesTestSetCreate: core.serialization.Schema<
    serializers.LibDtoTypesTestSetCreate.Raw,
    Scorecard.LibDtoTypesTestSetCreate
> = core.serialization.unknown();

export declare namespace LibDtoTypesTestSetCreate {
    type Raw = unknown;
}
