/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const LibDtoTypesCreateRunParams: core.serialization.Schema<
    serializers.LibDtoTypesCreateRunParams.Raw,
    Scorecard.LibDtoTypesCreateRunParams
> = core.serialization.unknown();

export declare namespace LibDtoTypesCreateRunParams {
    type Raw = unknown;
}
