/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const LibDtoTypesTestRecordCreate: core.serialization.Schema<
    serializers.LibDtoTypesTestRecordCreate.Raw,
    Scorecard.LibDtoTypesTestRecordCreate
> = core.serialization.unknown();

export declare namespace LibDtoTypesTestRecordCreate {
    type Raw = unknown;
}
