/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const ModelParams: core.serialization.Schema<serializers.ModelParams.Raw, Scorecard.ModelParams> =
    core.serialization.unknown();

export declare namespace ModelParams {
    type Raw = unknown;
}
