/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const PaginatedTestCaseResponse: core.serialization.ObjectSchema<
    serializers.PaginatedTestCaseResponse.Raw,
    Scorecard.PaginatedTestCaseResponse
> = core.serialization.object({
    count: core.serialization.number(),
    next: core.serialization.string().optional(),
    previous: core.serialization.string().optional(),
    results: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).TestCase)),
});

export declare namespace PaginatedTestCaseResponse {
    interface Raw {
        count: number;
        next?: string | null;
        previous?: string | null;
        results: serializers.TestCase.Raw[];
    }
}
