/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scorecard from "../../api/index";
import * as core from "../../core";
import { PromptModelParamsValue } from "./PromptModelParamsValue";

export const Prompt: core.serialization.ObjectSchema<serializers.Prompt.Raw, Scorecard.Prompt> =
    core.serialization.object({
        orgId: core.serialization.property("org_id", core.serialization.string().optional()),
        userId: core.serialization.property("user_id", core.serialization.string().optional()),
        id: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
        description: core.serialization.string().optional(),
        isArchived: core.serialization.property("is_archived", core.serialization.boolean().optional()),
        promptTemplate: core.serialization.property("prompt_template", core.serialization.string().optional()),
        modelParams: core.serialization.property(
            "model_params",
            core.serialization.record(core.serialization.string(), PromptModelParamsValue.optional()).optional()
        ),
        rootId: core.serialization.property("root_id", core.serialization.string().optional()),
        parentId: core.serialization.property("parent_id", core.serialization.string().optional()),
        mergeParentId: core.serialization.property("merge_parent_id", core.serialization.string().optional()),
        createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
        projectId: core.serialization.property("project_id", core.serialization.number().optional()),
    });

export declare namespace Prompt {
    interface Raw {
        org_id?: string | null;
        user_id?: string | null;
        id?: string | null;
        name?: string | null;
        description?: string | null;
        is_archived?: boolean | null;
        prompt_template?: string | null;
        model_params?: Record<string, PromptModelParamsValue.Raw | null | undefined> | null;
        root_id?: string | null;
        parent_id?: string | null;
        merge_parent_id?: string | null;
        created_at?: string | null;
        project_id?: number | null;
    }
}
