/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const RunStatus: core.serialization.Schema<serializers.RunStatus.Raw, Scorecard.RunStatus> =
    core.serialization.enum_([
        "pending",
        "awaiting_execution",
        "running_execution",
        "awaiting_scoring",
        "running_scoring",
        "awaiting_human_scoring",
        "completed",
    ]);

export declare namespace RunStatus {
    type Raw =
        | "pending"
        | "awaiting_execution"
        | "running_execution"
        | "awaiting_scoring"
        | "running_scoring"
        | "awaiting_human_scoring"
        | "completed";
}
