/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const ScoreExecutionParams: core.serialization.Schema<
    serializers.ScoreExecutionParams.Raw,
    Scorecard.ScoreExecutionParams
> = core.serialization.unknown();

export declare namespace ScoreExecutionParams {
    type Raw = unknown;
}
