/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scorecard from "../../api/index";
import * as core from "../../core";

export const ScoreStatus: core.serialization.Schema<serializers.ScoreStatus.Raw, Scorecard.ScoreStatus> =
    core.serialization.enum_(["pending", "error", "completed"]);

export declare namespace ScoreStatus {
    type Raw = "pending" | "error" | "completed";
}
