/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const ScoringParams: core.serialization.Schema<serializers.ScoringParams.Raw, Scorecard.ScoringParams> =
    core.serialization.unknown();

export declare namespace ScoringParams {
    type Raw = unknown;
}
