/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scorecard from "../../api/index";
import * as core from "../../core";
import { FileUrl } from "./FileUrl";

export const TestrecordCustomLabelsValue: core.serialization.Schema<
    serializers.TestrecordCustomLabelsValue.Raw,
    Scorecard.TestrecordCustomLabelsValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    FileUrl,
    core.serialization.lazyObject(() => serializers.JsonObject),
]);

export declare namespace TestrecordCustomLabelsValue {
    type Raw = string | FileUrl.Raw | serializers.JsonObject.Raw;
}
