/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scorecard from "../../api/index";
import * as core from "../../core";
import { FileUrl } from "./FileUrl";

export const TestrecordCustomInputsValue: core.serialization.Schema<
    serializers.TestrecordCustomInputsValue.Raw,
    Scorecard.TestrecordCustomInputsValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    FileUrl,
    core.serialization.lazyObject(async () => (await import("..")).JsonObject),
]);

export declare namespace TestrecordCustomInputsValue {
    type Raw = string | FileUrl.Raw | serializers.JsonObject.Raw;
}
