/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const TestSetExternal: core.serialization.ObjectSchema<
    serializers.TestSetExternal.Raw,
    Scorecard.TestSetExternal
> = core.serialization.object({
    id: core.serialization.number().optional(),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    usingRetrieval: core.serialization.property("using_retrieval", core.serialization.boolean().optional()),
    ingestionMethod: core.serialization.property("ingestion_method", core.serialization.string().optional()),
    numTestcases: core.serialization.property("num_testcases", core.serialization.number().optional()),
    published: core.serialization.boolean().optional(),
    updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
    isArchived: core.serialization.property("is_archived", core.serialization.boolean().optional()),
    projectId: core.serialization.property("project_id", core.serialization.number().optional()),
    customInputsSchema: core.serialization.property(
        "custom_inputs_schema",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
    ),
    customLabelsSchema: core.serialization.property(
        "custom_labels_schema",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
    ),
    customOutputsSchema: core.serialization.property(
        "custom_outputs_schema",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
    ),
});

export declare namespace TestSetExternal {
    interface Raw {
        id?: number | null;
        created_at?: string | null;
        name?: string | null;
        description?: string | null;
        using_retrieval?: boolean | null;
        ingestion_method?: string | null;
        num_testcases?: number | null;
        published?: boolean | null;
        updated_at?: string | null;
        is_archived?: boolean | null;
        project_id?: number | null;
        custom_inputs_schema?: Record<string, unknown> | null;
        custom_labels_schema?: Record<string, unknown> | null;
        custom_outputs_schema?: Record<string, unknown> | null;
    }
}
