/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const Testrecord: core.serialization.ObjectSchema<serializers.Testrecord.Raw, Scorecard.Testrecord> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
        runId: core.serialization.property("run_id", core.serialization.number()),
        testsetId: core.serialization.property("testset_id", core.serialization.number()),
        userQuery: core.serialization.property("user_query", core.serialization.string()),
        context: core.serialization.string().optional(),
        modelResponse: core.serialization.property("model_response", core.serialization.string().optional()),
        ideal: core.serialization.string().optional(),
        fullPrompt: core.serialization.property("full_prompt", core.serialization.string().optional()),
        customInputs: core.serialization.property(
            "custom_inputs",
            core.serialization
                .record(
                    core.serialization.string(),
                    core.serialization.lazy(async () => (await import("..")).TestrecordCustomInputsValue).optional()
                )
                .optional()
        ),
        customLabels: core.serialization.property(
            "custom_labels",
            core.serialization
                .record(
                    core.serialization.string(),
                    core.serialization.lazy(async () => (await import("..")).TestrecordCustomLabelsValue).optional()
                )
                .optional()
        ),
        customOutputs: core.serialization.property(
            "custom_outputs",
            core.serialization
                .record(
                    core.serialization.string(),
                    core.serialization.lazy(async () => (await import("..")).TestrecordCustomOutputsValue).optional()
                )
                .optional()
        ),
    });

export declare namespace Testrecord {
    interface Raw {
        id?: number | null;
        created_at?: string | null;
        run_id: number;
        testset_id: number;
        user_query: string;
        context?: string | null;
        model_response?: string | null;
        ideal?: string | null;
        full_prompt?: string | null;
        custom_inputs?: Record<string, serializers.TestrecordCustomInputsValue.Raw | null | undefined> | null;
        custom_labels?: Record<string, serializers.TestrecordCustomLabelsValue.Raw | null | undefined> | null;
        custom_outputs?: Record<string, serializers.TestrecordCustomOutputsValue.Raw | null | undefined> | null;
    }
}
