/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const TestRecordCreate: core.serialization.Schema<serializers.TestRecordCreate.Raw, Scorecard.TestRecordCreate> =
    core.serialization.unknown();

export declare namespace TestRecordCreate {
    type Raw = unknown;
}
