/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const TestCase: core.serialization.ObjectSchema<serializers.TestCase.Raw, Scorecard.TestCase> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
        testsetId: core.serialization.property("testset_id", core.serialization.number()),
        userQuery: core.serialization.property("user_query", core.serialization.string()),
        context: core.serialization.string().optional(),
        response: core.serialization.string().optional(),
        ideal: core.serialization.string().optional(),
        fullPrompt: core.serialization.property("full_prompt", core.serialization.string().optional()),
        customInputs: core.serialization.property(
            "custom_inputs",
            core.serialization.lazy(async () => (await import("..")).TestCaseCustomInputs).optional()
        ),
        customLabels: core.serialization.property(
            "custom_labels",
            core.serialization.lazy(async () => (await import("..")).TestCaseCustomLabels).optional()
        ),
    });

export declare namespace TestCase {
    interface Raw {
        id?: number | null;
        created_at?: string | null;
        testset_id: number;
        user_query: string;
        context?: string | null;
        response?: string | null;
        ideal?: string | null;
        full_prompt?: string | null;
        custom_inputs?: serializers.TestCaseCustomInputs.Raw | null;
        custom_labels?: serializers.TestCaseCustomLabels.Raw | null;
    }
}
