/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scorecard from "../../api/index";
import * as core from "../../core";
import { FileUrl } from "./FileUrl";

export const TestCaseCustomLabelsValue: core.serialization.Schema<
    serializers.TestCaseCustomLabelsValue.Raw,
    Scorecard.TestCaseCustomLabelsValue
> = core.serialization.undiscriminatedUnion([
    FileUrl,
    core.serialization.lazyObject(async () => (await import("..")).JsonObject),
    core.serialization.string(),
    core.serialization.number(),
    core.serialization.number(),
    core.serialization.boolean(),
]);

export declare namespace TestCaseCustomLabelsValue {
    type Raw = FileUrl.Raw | serializers.JsonObject.Raw | string | number | number | boolean;
}
