/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const TestCaseCustomLabelsValue: core.serialization.Schema<
    serializers.TestCaseCustomLabelsValue.Raw,
    Scorecard.TestCaseCustomLabelsValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("..")).FileUrl),
    core.serialization.unknown(),
]);

export declare namespace TestCaseCustomLabelsValue {
    type Raw = string | serializers.FileUrl.Raw | unknown;
}
