/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scorecard from "../../api/index";
import * as core from "../../core";

export const TestSetCreate: core.serialization.Schema<serializers.TestSetCreate.Raw, Scorecard.TestSetCreate> =
    core.serialization.unknown();

export declare namespace TestSetCreate {
    type Raw = unknown;
}
