/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scorecard from "../../api/index";
import * as core from "../../core";
import { TestCaseCustomInputsValue } from "./TestCaseCustomInputsValue";
import { TestCaseCustomLabelsValue } from "./TestCaseCustomLabelsValue";

export const TestCase: core.serialization.ObjectSchema<serializers.TestCase.Raw, Scorecard.TestCase> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
        testsetId: core.serialization.property("testset_id", core.serialization.number()),
        userQuery: core.serialization.property("user_query", core.serialization.string()),
        context: core.serialization.string().optional(),
        ideal: core.serialization.string().optional(),
        customInputs: core.serialization.property(
            "custom_inputs",
            core.serialization.record(core.serialization.string(), TestCaseCustomInputsValue.optional()).optional()
        ),
        customLabels: core.serialization.property(
            "custom_labels",
            core.serialization.record(core.serialization.string(), TestCaseCustomLabelsValue.optional()).optional()
        ),
    });

export declare namespace TestCase {
    interface Raw {
        id?: number | null;
        created_at?: string | null;
        testset_id: number;
        user_query: string;
        context?: string | null;
        ideal?: string | null;
        custom_inputs?: Record<string, TestCaseCustomInputsValue.Raw | null | undefined> | null;
        custom_labels?: Record<string, TestCaseCustomLabelsValue.Raw | null | undefined> | null;
    }
}
