/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const TestCaseCustomLabels: core.serialization.Schema<
    serializers.TestCaseCustomLabels.Raw,
    Scorecard.TestCaseCustomLabels
> = core.serialization.undiscriminatedUnion([
    core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    core.serialization.list(core.serialization.unknown()),
]);

export declare namespace TestCaseCustomLabels {
    type Raw = Record<string, unknown> | unknown[];
}
