/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const TestCaseCreateInput: core.serialization.Schema<
    serializers.TestCaseCreateInput.Raw,
    Scorecard.TestCaseCreateInput
> = core.serialization.unknown();

export declare namespace TestCaseCreateInput {
    type Raw = unknown;
}
