/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scorecard from "../../api/index";
import * as core from "../../core";

export const TestcaseBatchDeletionResponse: core.serialization.ObjectSchema<
    serializers.TestcaseBatchDeletionResponse.Raw,
    Scorecard.TestcaseBatchDeletionResponse
> = core.serialization.object({
    ids: core.serialization.list(core.serialization.number()),
    detail: core.serialization.string(),
});

export declare namespace TestcaseBatchDeletionResponse {
    interface Raw {
        ids: number[];
        detail: string;
    }
}
