/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const TestCaseCustomInputs: core.serialization.Schema<
    serializers.TestCaseCustomInputs.Raw,
    Scorecard.TestCaseCustomInputs
> = core.serialization.undiscriminatedUnion([
    core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    core.serialization.list(core.serialization.unknown()),
]);

export declare namespace TestCaseCustomInputs {
    type Raw = Record<string, unknown> | unknown[];
}
