/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Scorecard from "../../api";
import * as core from "../../core";

export const TestCaseCustomInputsValue: core.serialization.Schema<
    serializers.TestCaseCustomInputsValue.Raw,
    Scorecard.TestCaseCustomInputsValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("..")).FileUrl),
    core.serialization.lazyObject(async () => (await import("..")).JsonObject),
]);

export declare namespace TestCaseCustomInputsValue {
    type Raw = string | serializers.FileUrl.Raw | serializers.JsonObject.Raw;
}
