/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scorecard from "../../api/index";
import * as core from "../../core";

export const Trace: core.serialization.ObjectSchema<serializers.Trace.Raw, Scorecard.Trace> = core.serialization.object(
    {
        traceId: core.serialization.property("TraceId", core.serialization.string()),
        start: core.serialization.property("Start", core.serialization.date()),
        end: core.serialization.property("End", core.serialization.date()),
    }
);

export declare namespace Trace {
    interface Raw {
        TraceId: string;
        Start: string;
        End: string;
    }
}
