/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         isArchived: true
 *     }
 */
export interface PromptUpdateParams {
    isArchived?: boolean;
    isProd?: boolean;
}
