/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface PromptGetByNameRequest {
    /**
     * Name of the prompt.
     */
    name: string;
    /**
     * Tag to select by. Defaults to selecting the production version
     */
    tag?: string;
}
