/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "../../../../index";

/**
 * @example
 *     {
 *         promptTemplate: "You are a virtual assistant",
 *         name: "Prompt Name",
 *         description: "Description of the prompt",
 *         modelParams: {
 *             "param1": "value1",
 *             "param2": 0.1,
 *             "param3": 100,
 *             "param4": true
 *         }
 *     }
 *
 * @example
 *     {
 *         promptTemplate: "You are a virtual assistant",
 *         parentId: "7ac3cbd5-3b99-4e72-97f3-9cd2e749cace",
 *         description: "Description of the prompt",
 *         modelParams: {
 *             "param1": "value1",
 *             "param2": 0.1,
 *             "param3": 100,
 *             "param4": true
 *         },
 *         isProd: true
 *     }
 */
export interface PromptCreateParams {
    promptTemplate: string;
    name?: string;
    parentId?: string;
    description?: string;
    modelParams?: Record<string, Scorecard.PromptCreateParamsModelParamsValue | undefined>;
    isProd?: boolean;
}
