/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "../../../../index";

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface TestsetCreateParams {
    name: string;
    description?: string;
    usingRetrieval?: boolean;
    customSchema?: Scorecard.CustomSchema;
}
