/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "../../../../index";

/**
 * @example
 *     {}
 */
export interface TestsetUpdateParams {
    name?: string;
    /** A description for the testset. */
    description?: string;
    /** Whether or not the testset uses retrieval. */
    usingRetrieval?: boolean;
    customSchema?: Scorecard.CustomSchema;
}
