/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scorecard from "../../../../../api/index";
import * as core from "../../../../../core";

export const ScoringConfigCreateParams: core.serialization.Schema<
    serializers.ScoringConfigCreateParams.Raw,
    Scorecard.ScoringConfigCreateParams
> = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    metrics: core.serialization.list(core.serialization.number()).optional(),
    projectId: core.serialization.property("project_id", core.serialization.number().optional()),
});

export declare namespace ScoringConfigCreateParams {
    interface Raw {
        name?: string | null;
        description?: string | null;
        metrics?: number[] | null;
        project_id?: number | null;
    }
}
