/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ScorecardEnvironment = {
    Default: "https://api.getscorecard.ai",
} as const;

export type ScorecardEnvironment = typeof ScorecardEnvironment.Default;
