/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface TestcaseBatchDeleteParams {
    /** List of Testcase IDs to delete. */
    ids?: number[];
}
