/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "../../../../index";

/**
 * @example
 *     {}
 */
export interface TestcaseCreateParams {
    /** The user query to be executed. */
    userQuery?: string;
    /** The context to be used while generating the testcase. */
    context?: string;
    /** The ideal response to the user query. */
    ideal?: string;
    customInputs?: Record<string, Scorecard.TestcaseCreateParamsCustomInputsValue | undefined>;
    customLabels?: Record<string, Scorecard.TestcaseCreateParamsCustomLabelsValue | undefined>;
}
