/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface TestcaseBatchCopyParams {
    /** List of Testcase IDs to copy. */
    ids?: number[];
}
