/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scorecard from "../../../../index";

/**
 * @example
 *     {
 *         userQuery: "user_query"
 *     }
 */
export interface TestcaseCreateParams {
    userQuery: string;
    context?: string;
    ideal?: string;
    customInputs?: Record<string, Scorecard.TestcaseCreateParamsCustomInputsValue | undefined>;
    customLabels?: Record<string, Scorecard.TestcaseCreateParamsCustomLabelsValue | undefined>;
}
