/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scorecard from "../../../../../api/index";
import * as core from "../../../../../core";

export const TestcaseBatchDeleteParams: core.serialization.Schema<
    serializers.TestcaseBatchDeleteParams.Raw,
    Scorecard.TestcaseBatchDeleteParams
> = core.serialization.object({
    ids: core.serialization.list(core.serialization.number()).optional(),
});

export declare namespace TestcaseBatchDeleteParams {
    interface Raw {
        ids?: number[] | null;
    }
}
