/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scorecard from "../../../../../api/index";
import * as core from "../../../../../core";
import { TestcaseUpdateParamsCustomInputsValue } from "../../types/TestcaseUpdateParamsCustomInputsValue";
import { TestcaseUpdateParamsCustomLabelsValue } from "../../types/TestcaseUpdateParamsCustomLabelsValue";

export const TestcaseUpdateParams: core.serialization.Schema<
    serializers.TestcaseUpdateParams.Raw,
    Scorecard.TestcaseUpdateParams
> = core.serialization.object({
    userQuery: core.serialization.property("user_query", core.serialization.string().optional()),
    context: core.serialization.string().optional(),
    ideal: core.serialization.string().optional(),
    customInputs: core.serialization.property(
        "custom_inputs",
        core.serialization
            .record(core.serialization.string(), TestcaseUpdateParamsCustomInputsValue.optional())
            .optional()
    ),
    customLabels: core.serialization.property(
        "custom_labels",
        core.serialization
            .record(core.serialization.string(), TestcaseUpdateParamsCustomLabelsValue.optional())
            .optional()
    ),
});

export declare namespace TestcaseUpdateParams {
    interface Raw {
        user_query?: string | null;
        context?: string | null;
        ideal?: string | null;
        custom_inputs?: Record<string, TestcaseUpdateParamsCustomInputsValue.Raw | null | undefined> | null;
        custom_labels?: Record<string, TestcaseUpdateParamsCustomLabelsValue.Raw | null | undefined> | null;
    }
}
