/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scorecard from "../../../../api/index";
import * as core from "../../../../core";
import { Trace } from "../../../types/Trace";

export const Response: core.serialization.Schema<serializers.tracing.traces.Response.Raw, Scorecard.Trace[]> =
    core.serialization.list(Trace);

export declare namespace Response {
    type Raw = Trace.Raw[];
}
